### ISSUE TITLE
one thread acquire the lock while another thread changed the value of the lock in redis

### ISSUE THREAD

**Issue by Martian101** [abelaska/jedis-lock#5]
Hi! In the acquire method when the lock is expired, if one thread, like _thread A_,  has getSet the lock in redis but doesn't get into subsequent statements while another thread, like _thread B_,  changed the value of the lock in redis, then _thread A_ will fail to reentry the lock because the value of the lock in redis is not same as what _thread A_ has.And _thread B_ will get the lock next turn while _Thread A_ still owns it.
I think I can change the code as below to solve such problem:

``` java
            if (currentLock.isExpiredOrMine(lockUUID)) {
                String oldValueStr = jedis.getSet(lockKeyPath, newLock.toString());
                if (oldValueStr != null && oldValueStr.equals(currentValueStr)) {
                    jedis.set(lockKeyPath, newLock.toString());
                    this.lock = newLock;
                    return true;
                }
            }
```

**Comment by t3573393** [comment]
Above code will make the Thread b not the same with the redis. So i think the below code is not safe.

`
            final String currentValueStr = jedis.get(lockKeyPath);
            final Lock currentLock = Lock.fromString(currentValueStr);
            if (currentLock.isExpiredOrMine(lockUUID)) {
                String oldValueStr = jedis.getSet(lockKeyPath, newLock.toString());
`,

it can change use the setex to lock the time in the redis

**Comment by jenda** [comment]
according to me, the right solution is to use transactions for this:

```
        jedis.watch(lockKeyPath);
        final String currentValueStr = jedis.get(lockKeyPath);
        final Transaction t = jedis.multi();
        final Lock currentLock = Lock.fromString(currentValueStr);
        if (currentLock.isExpiredOrMine(lockUUID)) {
            Result<String> oldValueStrRes = t.getSet(lockKeyPath, newLock.toString());
            if (t.exec() == null) {
              // someone updated the value
              continue;
            }
            if (oldValueStr != null && oldValueStrRes.get().equals(currentValueStr)) {
                this.lock = newLock;
                return true;
            }
        }
```
